### ISSUE TITLE
Materialデザインの適用

### ISSUE THREAD

**Issue by pollseed** [springhackathon/spa-service#9]
## まずは調査から

[Material ui](http://material-ui.com/)
## HTMLへの適用

node.jsのコミット後適用させる
## スコープ

~~https://github.com/DreamHackers/fx-future-forecast/blob/master/index.html~~

**Comment by kouares** [comment]
## 調査結果

[Material ui](http://material-ui.com/) はReact全開で使用するフレームワークだった
bootstrap感覚で使えるイメージだっけど大分ちがってるから使わない

むしろ、bootstrap感覚なのは [Material Design Lite](http://www.getmdl.io/index.html)だったのでこっちを使うことで決定

**Comment by pollseed** [comment]
done
